services:
  - type: web
    name: newssnap
    env: docker
    dockerfilePath: ./Dockerfile.render
    autoDeploy: true
    healthCheckPath: /health
    plan: free
    envVars:
      - key: MODEL_DIR
        value: models/latest
